# Data managment principles





<div class="azure"> 


Applying the Guerrilla analytics framework to your own project.

    Look at your RStudio project that you created for the DAUR-II assignments
    download your folders (not the HUGE datafiles and kraken-database!) and rearrange your project according the Guerilla principles explained above
    for the data… folders: provide only a readme.txt with alle the info you would normally put there + where the data is stored
    Provide study documentation and meta data.
    Use the {fs} package to share a screenshot of your folder tree in your portfolio, look at: for more info on how to use the {fs} package.

hint: you had 3 datasets within the RNAseq project, one of them being the exam project, and 2 datasets within the metagenomics project.

    Now clean up your work environment for this course (workflows) and the parallel course in DSFB2 (projecticum). Set up a folder structure that will accomodate future plans and collaboration on the projecticum. Provide readme-files or comments within the code where needed.

For the projecticum folder, make sure you do this together with your lab partner.

</div>
